### ISSUE TITLE
getting ReferenceError: handlerParent is not defined

### ISSUE THREAD

**Issue by bsommers** [slidewiki/reflux-analysis#3]
Hi,

I'm getting a ReferenceError: handlerParent is not defined 

< searching for /client/components/Application.js
break in timers.js:557
 555     threw = false;
 556   } finally {
>557     if (threw && !L.isEmpty(queue)) {
 558       // Handle any remaining on next tick, assuming we're still alive to do so.
 559       while (!L.isEmpty(immediateQueue)) {
debug> 
< /home/jdoe/src/reflux-analysis/node_modules/synchronize/sync.js:114
<         fiber.run(result)
<               ^
< ReferenceError: handlerParent is not defined
<     at resolveRelations (/home/jdoe/src/reflux-analysis/reflux-analyzer.js:68:50)
<     at Function.<anonymous> (/home/jdoe/src/reflux-analysis/reflux-analyzer.js:167:19)
<     at /home/jdoe/src/reflux-analysis/node_modules/synchronize/sync.js:281:10
program terminated

**Comment by bwulff** [comment]
Thanks for reporting @bsommers !
